---
- name: Install Nginx
  yum: name=nginx state=present
  tags:
    - nginx

# - name: Copy Nginx Configuration for Wordpress
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx

# - name: insert firewalld rule for nginx
#   firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
#   ignore_errors: yes

- name: Nginx move sites.conf files
  template: src=sites.conf dest=/etc/nginx/conf.d/
  tags:
    - nginx
  notify:
    - restart nginx
