---
# tasks file for roles/hadoop

# install the packages
- name: Download hadoop-2.7.4.tar.gz from internet
  get_url:
    url: http://mirror.bit.edu.cn/apache/hadoop/common/hadoop-2.7.4/hadoop-2.7.4.tar.gz
    dest: /opt/hadoop-2.7.4.tar.gz
    checksum: sha256:8f791bfcfa5bb7c7ccd09910d490c02910dda93b19936ec2aedb8930bc5be111
    timeout: 60
  tags:
    - hadoop

- name: Unarchive the hadoop-2.7.4 file.
  unarchive:
    src: "/opt/hadoop-2.7.4.tar.gz"
    dest: "/opt/"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  tags:
    - hadoop

- name: Making sub-directories for hadoop
  file:
    path: '/opt/hadoop-2.7.4/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - tmp
    - hdfs
    - hdfs/namenode
    - hdfs/tmp
    - hdfs/datanode
  tags:
    - hadoop

# configure env
- name: Disable ipv6 on nodes
  sysctl:
    name: '{{ item }}'
    value: 1
    sysctl_file: '/etc/sysctl.conf'
  with_items:
    - 'net.ipv6.conf.all.disable_ipv6'
    - 'net.ipv6.conf.default.disable_ipv6'
    - 'net.ipv6.conf.lo.disable_ipv6'
  tags:
    - hadoopv

- name: settings to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: "{{item}}"
  with_items:
    - " "
    - "## Setting JAVA_HOME and PATH for all USERS ##"
    - "export JAVA_HOME=/opt/jdk1.8.0_144"
    - "export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
    - "export HADOOP_HOME=/opt/hadoop-2.7.4"
    - "export HADOOP_PREFIX=$HADOOP_HOME"
    - "export YARN_HOME=$HADOOP_HOME"
    - "export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop"
    - "export HADOOP_LOG_DIR=$HADOOP_HOME/logs"
    - "export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin/:$HADOOP_HOME/sbin/"
  tags:
    - hadoop

- name: Update core-site.xml for master
  copy:
    src: "{{ item }}"
    dest: "/opt/hadoop-2.7.4/etc/hadoop/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - masters
    - slaves
    - yarn-site.xml
  tags:
    - hadoop

# service 
