---
# tasks file for roles/hadoop

# install the packages
- name: Download hadoop-{{ hadoop_version }}.tar.gz from internet
  get_url:
    url: http://mirror.bit.edu.cn/apache/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz
    dest: /opt/hadoop-{{ hadoop_version }}.tar.gz
    checksum: sha256:{{ hadoop_sha256 }}
    timeout: 60
  tags:
    - hadoop
    - hadoopi

- name: Unarchive the hadoop-{{ hadoop_version }} file.
  unarchive:
    src: "/opt/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "/opt/"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  tags:
    - hadoop
    - hadoopi

- name: Making sub-directories for hadoop
  file:
    path: '/opt/hadoop-{{ hadoop_version }}/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - tmp
    - hdfs
    - hdfs/namenode
    - hdfs/tmp
    - hdfs/datanode
  tags:
    - hadoop
    - hadoopi

# configure env
- name: Disable ipv6 on nodes
  sysctl:
    name: '{{ item }}'
    value: 1
    sysctl_file: '/etc/sysctl.conf'
  with_items:
    - 'net.ipv6.conf.all.disable_ipv6'
    - 'net.ipv6.conf.default.disable_ipv6'
    - 'net.ipv6.conf.lo.disable_ipv6'
  tags:
    - hadoop
    - hadoopc

- name: settings to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: "{{item}}"
  with_items:
    - " "
    - "## Setting JAVA_HOME and PATH for all USERS ##"
    - "export JAVA_HOME=/opt/jdk1.8.0_144"
    - "export HADOOP_HOME=/opt/hadoop-{{ hadoop_version }}"
    - "export HADOOP_PREFIX=$HADOOP_HOME"
    - "export YARN_HOME=$HADOOP_HOME"
    - "export HADOOP_MAPRED_HOME=$HADOOP_HOME"
    - "export HADOOP_COMMON_HOME=$HADOOP_HOME"
    - "export HADOOP_HDFS_HOME=$HADOOP_HOME"
    - "export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop"
    - "export HADOOP_LOG_DIR=$HADOOP_HOME/logs" 
    - "export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
    - "export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin/:$HADOOP_HOME/sbin/:$PATH"
  tags:
    - hadoop
    - hadoopc

- name: Update core-site.xml for master
  template:
    src: "{{ item }}"
    dest: "/opt/hadoop-{{ hadoop_version }}/etc/hadoop/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - masters
    - slaves
    - yarn-site.xml
  tags:
    - hadoop
    - hadoopc

# - name: Testing hostnames
#   debug:
#     msg: "= {{inventory_hostname }} ="
#   when: "inventory_hostname == 'master' or inventory_hostname == 'slave1'"
#   tags:
#     - hadoopd


# # service 
# - name: Start hdfs and yarn service
#   command: /opt/hadoop-{{ hadoop_version }}/bin/hdfs namenode -format
#   environment:
#     JAVA_HOME: /opt/jdk1.8.0_144
#     HADOOP_HOME: /opt/hadoop-{{ hadoop_version }}
#     HADOOP_PREFIX: /opt/hadoop-{{ hadoop_version }}
#     HADOOP_HDFS_HOME: /opt/hadoop-{{ hadoop_version }}
#   when: "inventory_hostname == 'master'"
#   tags:
#     - hadoopd



