---
# tasks file for java8

- name: Download the jdk-8u131
  get_url:
    url: http://ftp.heanet.ie/mirrors/funtoo/distfiles/oracle-java/jdk-8u131-linux-x64.tar.gz
    dest: /opt/jdk-8u131-linux-x64.tar.gz
    timeout: 30
  tags:
    - java

- name: unarchive the jdk-8u131 file.
  unarchive:
    src: "/opt/jdk-8u131-linux-x64.tar.gz"
    dest: "/opt/"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  tags:
    - java

- name: Alternatives link to installed java
  alternatives:
    name: java
    link: /usr/bin/java
    path: /opt/jdk1.8.0_131/bin/java
    priority: 2
  tags:
    - java

- name: Alternatives link to installed javaws
  alternatives:
    name: javaws
    link: /usr/bin/javaws
    path: /opt/jdk1.8.0_131/bin/javaws
    priority: 2
  tags:
    - java

- name: Alternatives link to installed javac
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: /opt/jdk1.8.0_131/bin/javac
    priority: 2
  tags:
    - java

- name: Alternatives link to installed javap
  alternatives:
    name: javap
    link: /usr/bin/javap
    path: /opt/jdk1.8.0_131/bin/javap
    priority: 2
  tags:
    - java

- name: Alternatives link to installed jar
  alternatives:
    name: jar
    link: /usr/bin/jar
    path: /opt/jdk1.8.0_131/bin/jar
    priority: 2
  tags:
    - java

- name: Alternatives link to installed jps
  alternatives:
    name: jps
    link: /usr/bin/jps
    path: /opt/jdk1.8.0_131/bin/jps
    priority: 2
  tags:
    - java

- name: Add lines to /etc/profile file
  lineinfile:
    path: /etc/profile
    line: "{{item}}"
  with_items:
    - " "
    - "## Setting JAVA_HOME and PATH for all USERS ##"
    - "export JAVA_HOME=/opt/jdk1.8.0_131"
    - "export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
    - "export PATH=$PATH:$JAVA_HOME/bin"
  tags:
    - javal
