---
# tasks file for java8

- name: Download the jdk-8u144
  get_url:
    url: http://ftp.heanet.ie/mirrors/funtoo/distfiles/oracle-java/jdk-8u144-linux-x64.tar.gz
    dest: /opt/jdk-8u144-linux-x64.tar.gz
    timeout: 30
  tags:
    - java

- name: Unarchive the jdk-8u144 file.
  unarchive:
    src: "/opt/jdk-8u144-linux-x64.tar.gz"
    dest: "/opt/"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  tags:
    - java

- name: Alternatives link to installed java
  alternatives:
    name: "{{item}}"
    link: "/usr/bin/{{item}}"
    path: "/opt/jdk1.8.0_144/bin/{{item}}"
    priority: 2
  with_items:
    - 'java'
    - 'javaws'
    - 'javac'
    - 'javap'
    - 'jar'
    - 'jps'
  tags:
    - java

- name: Add lines to /etc/profile file
  lineinfile:
    path: /etc/profile
    line: "{{item}}"
  with_items:
    - " "
    - "## Setting JAVA_HOME and PATH for all USERS ##"
    - "export JAVA_HOME=/opt/jdk1.8.0_144"
    - "export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
    - "export PATH=$PATH:$JAVA_HOME/bin"
  tags:
    - java
