---
- name: Setup the environment of docker-jenkins
  # hosts: test.boe
  hosts: git.ct.boe.com.cn
  # hosts: boe-server
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     yum: name=* state=latest

  roles:
  # - docker-registry
  - docker-jenkins
  # post_tasks:
  #   - name: post tasks
  #     yum: name=* state=latest
