---
- name: Setup the environment of hadoop cluster
  hosts: hadoop
  become_user: root
  become: yes
  
  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     yum: name=* state=latest

  roles:
    - hadoop


  # post_tasks:
  #   - name: post tasks
  #     yum: name=* state=latest

