---
- name: Setup the environment of hadoop cluster
  hosts: hadoop-slave
  become_user: root
  become: yes
  
  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     yum: name=* state=latest

  roles:
    - java8
    - ssh
    - ntpd
    - hadoop-slave


  # post_tasks:
  #   - name: post tasks
  #     yum: name=* state=latest

