---
- name: Setup the environment of docker
  hosts: hadoop
  # hosts: git.ct.boe.com.cn
  # hosts: boe-server
  become_user: root
  become: yes
  
  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     yum: name=* state=latest

  roles:
    - java8
    - ssh
    - ntpd
    - postgres
    - cloudera


  # post_tasks:
  #   - name: post tasks
  #     yum: name=* state=latest

