---
- name: Install MariaDB, Nginx and PHP-FPM
  hosts: hpp-server
  become_user: root
  # remote_user: root
  # remote_user: user
  become: yes
  
  roles:
  - common
  - mariadb
  - httpd
  - php-fpm

  tasks:
    - name: checkout code
      git: repo=https://github.com/jinqiqiqi/ansible.git dest=/vagrant/able accept_hostkey=yes
