VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.provider "virtualbox" do |vb|
		# Display the VirtualBox GUI when booting the machine
		vb.gui = false

		# Customize the amount of memory on the VM:
		vb.memory = "1024"
	end


	config.vm.box = "centos77"
	config.vm.network "forwarded_port", guest: 80, host: 8888
	config.vm.network "forwarded_port", guest: 433, host: 8433
	# config.vm.synced_folder "/home/kinch/Public/hpp", "/usr/share/nginx/html/"
end
