---
# tasks file for roles/docker-jenkins

- name: Create directory for jenkins data
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ jenkins_data_dir }}"
    - "/etc/docker/certs.d/{{ registry_domain }}"
  tags:
    - docker-jenkins

- name: "Copy cert file to the server"
  template: src={{ registry_domain }}/ca.crt dest=/etc/docker/certs.d/{{ registry_domain }}/ca.crt
  tags:
    - docker-jenkins
  notify:
    - restart nginx

- name: "Login to {{ registry_domain }}"
  docker_login:
    registry: "{{ registry_domain }}"
    username: boe
    password: boe
  tags:
    - docker-jenkins

- name: "Pull docker jenkins image"
  docker_image: 
    name: "{{ item }}"
    state: present
    cacert_path: "/etc/docker/certs.d/{{ registry_domain }}/ca.crt"
  with_items:
    - "{{ registry_domain }}/jenkins"
  tags:
    - docker-jenkins
    

- name: Start/Restart docker jenkins container
  docker_container:
    image: "{{ registry_domain }}/jenkins"
    name: boe-jenkins
    hostname: "{{ jenkins_domain_name }}"
    state: started
    restart: yes
    env: 
    ports:
        - "{{ jenkins_web_port }}:8080"
        - "{{ jenkins_api_port }}:50000"
    volumes:
        - "{{ jenkins_data_dir }}:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/opt/apache-maven-3.5.0:/opt/apache-maven-3.5.0"
        - "/opt/jdk1.8.0_144:/opt/jdk1.8.0_144"
  tags:
    - docker-jenkins

- name: Update the nginx config
  template: src=jenkins.conf dest=/etc/nginx/conf.d/
  tags:
    - docker-jenkins
  notify:
    - restart nginx