---
# tasks file for roles/ceph



- name: Install Ceph Repository
  yum: name={{ item }} state=present
  with_items:
    - centos-release-ceph-hammer
  # notify: restart docker
  tags:
    - ceph

- name: Install Ceph Packages
  yum: name={{ item }} state=present
  with_items:
    - ceph
  notify: restart ceph
  tags:
    - ceph
