---
- name: Install httpd
  yum: name=httpd state=present
  # debug: msg={{wp_version}}
  tags:
    - centos
    - yum

# - name: Copy httpd Configuration for Wordpress
#   template: src=default.conf dest=/etc/httpd/conf.d/default.conf
#   notify: restart httpd

# - name: insert firewalld rule for httpd
#   firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes
#   ignore_errors: yes

- name: httpd Service State
  service: name=httpd state=started enabled=yes
