---
# tasks file for php
- name: Install PHP and PHP-FPM
  yum: name={{ item }} state=present
  tags:
    - php71
  with_items:
    - php71-php-mbstring
    - php71-php-mcrypt
    - php71-php
    - php71-php-gd
    - php71-php-fpm
    - php71-php-process
    - php71-php-xml
    - php71-php-pecl-memcached
    - php71-php-pecl-mysql
    - php71-php-pecl-zip
    - php71-php-pecl-redis

- name: Configuration to PHP
  template: src=php.ini.j2 dest=/etc/opt/remi/php71/php.ini
  tags:
    - php71
  notify: restart php71-php-fpm

- name: Configuration to PHP-FPM
  template: src=www.conf.j2 dest=/etc/opt/remi/php71/php-fpm.d/www.conf
  tags:
    - php71
  notify: restart php71-php-fpm